name: PixelmonGym
main: me.Ckay.gym.PlasmaGym
depend: [Vault]
version: 6.5
author: ABkayCkay
permissions:
  plasmagym.nomessage:
    description: Show no on join message!
  plasmagym.leader:
    description: Give access to Open/Close Gym.
  plasmagym.gym1:
    description: Leader is a Rock Gym Leader.
  plasmagym.gym2:
    description: Leader is a Electric Gym Leader.
  plasmagym.gym3:
    description: Leader is a Water Gym Leader.
  plasmagym.gym4:
    description: Leader is a Grass Gym Leader.
  plasmagym.gym5:
    description: Leader is a Poison Gym Leader.
  plasmagym.gym6:
    description: Leader is a Psychic Gym Leader. 
  plasmagym.gym7:
    description: Leader is a Fire Gym Leader. 
  plasmagym.gym8:
    description: Leader is a multi type Gym Leader.
  plasmagym.gym9:
    description: Leader is a Rock Gym Leader.
  plasmagym.gym10:
    description: Leader is a Electric Gym Leader.
  plasmagym.gym11:
    description: Leader is a Water Gym Leader.
  plasmagym.gym12:
    description: Leader is a Grass Gym Leader.
  plasmagym.gym13:
    description: Leader is a Poison Gym Leader.
  plasmagym.gym14:
    description: Leader is a Psychic Gym Leader. 
  plasmagym.gym15:
    description: Leader is a Fire Gym Leader. 
  plasmagym.gym16:
    description: Leader is a multi type Gym Leader.
  plasmagym.gym17:
    description: Leader is a Rock Gym Leader.
  plasmagym.gym18:
    description: Leader is a Electric Gym Leader.
  plasmagym.gym19:
    description: Leader is a Water Gym Leader.
  plasmagym.gym20:
    description: Leader is a Grass Gym Leader.
  plasmagym.gym21:
    description: Leader is a Poison Gym Leader.
  plasmagym.gym22:
    description: Leader is a Psychic Gym Leader. 
  plasmagym.gym23:
    description: Leader is a Fire Gym Leader. 
  plasmagym.gym24:
    description: Leader is a multi type Gym Leader.
  plasmagym.gym25:
    description: Leader is a Rock Gym Leader.
  plasmagym.gym26:
    description: Leader is a Electric Gym Leader.
  plasmagym.gym27:
    description: Leader is a Water Gym Leader.
  plasmagym.gym28:
    description: Leader is a Grass Gym Leader.
  plasmagym.gym29:
    description: Leader is a Poison Gym Leader.
  plasmagym.gym30:
    description: Leader is a Psychic Gym Leader. 
  plasmagym.gym31:
    description: Leader is a Fire Gym Leader. 
  plasmagym.gym32:
    description: Leader is a multi type Gym Leader.
  plasmagym.reload:
    description: Allows user to reload config.
  plasmagym.admin:
    description: Allows close all and future admin commands.
  plasmagym.e4leader:
    description: Leader of an e4.
  plasmagym.e41:
    description: Allows to open e4 level 1.
  plasmagym.e42:
    description: Allows to open e4 level 2.
  plasmagym.e43:
    description: Allows to open e4 level 3.
  plasmagym.e44:
    description: Allows to open e4 level 4.
commands:
   gym:
      description: Main Gym command
      usage: /gym
   e4:
      description: Main e4 Command
      usage: /e4
   plasmagym:
      description: Main admin command
      usage: /plasmagym